changelog:
  exclude:
    labels:
      - ignore-for-release
      - duplicate
      - wontfix
      - invalid
  categories:
    - title: 'Features'
      labels:
        - feat
        - enhancement
    - title: 'Bug Fixes'
      labels:
        - fix
        - bug
    - title: 'Performance Improvements'
      labels:
        - perf
        - performance
    - title: 'Documentation'
      labels:
        - docs
        - documentation
    - title: 'Maintenance'
      labels:
        - chore
        - ci
        - refactor
    - title: 'Dependencies'
      labels:
        - dependencies
    - title: 'Other Changes'
      labels:
        - '*'
